version: '3'
services:
  app:
    build: ./
    image: app:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Xmx512m
      DB_HOST: database
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: unitech
      DB_USERNAME: root
      DB_PASSWORD: example
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: database
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: unitech